version: "3.7"

services:
  json-server:
    container_name: database_json
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    ports:
      - "3000:3000"
    volumes:
      - ./database:/data
    
  frontend:
    container_name: vue_ui
    build: 
      context: .
      target: "develop-stage"
    volumes:
      - .:/app      
    ports:
      - "8083:8083"
    command: /bin/sh -c "yarn serve"
    
  test:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      -:/test
      
