version: "3.7"
services:

  backend:
    image: lab4-webapp:latest
    ports:
       - "3000:3000"    

  frontend:
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: frontendvue
    ports:
       - "8083:8083"     
    depends_on:
      - backend